# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      default:
        informational: true
    patch: off

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: 'diff, files'
  require_changes: true

# https://docs.codecov.com/docs/node
parsers:
  javascript:
    enable_partials: yes
