version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN: 9RRu36GLfbnk5Ri6Y6FpoZU10CW6dlIfy
  COVERALLS_SERVICE_NAME: appveyor
shallow_clone: true
build_script:
- ps: >-
    Install-Product node 0.12.0 x64

    npm install -g gulp

    npm cache clean

    npm install

    gulp flow-win

    gulp test --release true

    gulp coveralls
