version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN: 9RRu36GLfbnk5Ri6Y6FpoZU10CW6dlIfy
  COVERALLS_SERVICE_NAME: appveyor
shallow_clone: true
build_script:
- ps: >-
    Install-Product node 0.12.0 x64

    npm -g install npm@2

    set PATH=%APPDATA%\npm;%PATH%

    npm install -g gulp

    npm install

    gulp flow-win

    gulp test --release true

    gulp coveralls

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules
