version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN: ab4LZQwXbVRwQIn0MEHqaaOjidqu78RFQ
  COVERALLS_SERVICE_NAME: appveyor
shallow_clone: true
build_script:
- ps: >-
    Install-Product node 0.12.0 x64

    npm install -g gulp

    npm cache clean

    npm install

    gulp flow-win

    gulp test --release

    gulp coveralls
