# https://www.appveyor.com/docs/appveyor-yml/
shallow_clone: true
image: ubuntu
branches:
  only:
    - master
    - next

stack: node 12

install:
  - node --version
  - npm --version
  - npm install

before_build:
  - npm run eslint

build_script:
  - npm run build

test_script:
  - npm test

after_test:
  - npx codecov
