# https://www.appveyor.com/docs/appveyor-yml/
shallow_clone: true
image: Visual Studio 2017
branches:
  only:
    - master
    - next

environment:
  nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm install

before_build:
  - npm run eslint

build_script:
  - npm run build

test_script:
  - npm test
