name: CI
on:
  push:
    branches: [master, alpha, canary]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
    - name: npm install
      run: npm i
    - name: ESLint
      run: npm run eslint
    - name: Typecheck
      run: npm run typecheck
    - name: Test
      run: npm t -- --coverage --colors

  storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
    - uses: actions/cache@v1
      with:
        path: node_modules/.cache
        key: build-${{ hashFiles('package.json') }}
    - name: Build
      run: |
        npm i
        npm run build-storybook
    - name: Set up git user
      if: github.event_name == 'push'
      run: |
        git config --global user.email 'action@github.com'
        git config --global user.name 'GitHub Action'
    - name: Deploy master
      if: github.ref == 'refs/heads/master'
      run: |
        git checkout --orphan gh-pages
        git rm --cached $(git ls-files)
        git add -f storybook-static
        git mv storybook-static/* .
        git fetch origin gh-pages
        git checkout origin/gh-pages -- canary
        git commit -m "master storybook deployment"
        git push -f https://adazzle:${{secrets.GITHUB_TOKEN}}@github.com/adazzle/react-data-grid.git
    - name: Deploy canary
      if: github.ref == 'refs/heads/canary'
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        git rm -r --ignore-unmatch canary
        mv storybook-static canary
        git add canary
        git commit -m "canary storybook deployment"
        git push -f https://adazzle:${{secrets.GITHUB_TOKEN}}@github.com/adazzle/react-data-grid.git
