name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
      - name: npm install
        run: npm i
      - name: Biome
        run: npm run biome:ci
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier:check
      - name: Typecheck
        run: npm run typecheck
      - name: Bundle
        run: |
          npm run build
          npm run build:types
      - name: Test
        run: npm t
        timeout-minutes: 4
      - uses: codecov/codecov-action@v3

  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
      - uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: build-${{ hashFiles('package.json') }}
      - name: Build
        run: |
          npm i
          npm run build:website
      - name: Set up git user
        if: github.event_name == 'push'
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
      - name: Deploy gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages
          git rm -r .
          git checkout gh-pages -- old
          mv ../dist/* .
          git add .
          git commit -m "gh-pages deployment" || echo "Nothing to commit"
          git push -f https://adazzle:${{secrets.GITHUB_TOKEN}}@github.com/adazzle/react-data-grid.git
