name: CI
on:
  push:
    branches: [master, alpha, canary]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
    - uses: actions/cache@v1
      with:
        path: node_modules/.cache
        key: build-${{ hashFiles('package.json') }}
    - name: npm install
      run: npm i
    - name: ESLint
      run: npm run eslint
    - name: Typecheck
      run: npm run typecheck
    - name: Build storybook
      run: npm run build-storybook
    - name: Test
      run: npm t -- --coverage --colors
